default_install_hook_types: ["pre-commit", "commit-msg"]
default_stages: [commit]
minimum_pre_commit_version: 2.18.0

repos:
  - repo: "https://github.com/igorshubovych/markdownlint-cli"
    rev: v0.31.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        stages:
          - commit
        args:
          - "--prose-wrap"
          - "always"
