repos:
  - repo: "https://github.com/igorshubovych/markdownlint-cli"
    rev: v0.31.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        args:
          - "--prose-wrap"
          - "always"
